services:
  fastapi_app:
    build: .
    container_name: shifts_api
    ports:
      - "8001:8001"

    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@timescale_local:5432/${POSTGRES_DB}
      API_KEY: ${API_KEY}
      TZ: America/Santiago

    volumes:
      - .:/app

    restart: unless-stopped

    networks:
      - timescale_net

networks:
  timescale_net:
    external: true
    name: timescale-playground_default
